import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "@/app/globals.css";
import { SessionProvider } from "next-auth/react";
import { CommandMenu } from "@/components/ui/command-menu";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased font-[family-name:var(--font-outfit)]`}
      >
        <SessionProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>{children}</SidebarInset>
          </SidebarProvider>
        </SessionProvider>
        <CommandMenu />
      </body>
    </html>
  );
}
